name: Try to upload

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn

    - uses: calcit-lang/setup-cr@0.0.7
      with:
        bundler: false

    - run: caps --ci && yarn && yarn compile-page && yarn release-page

    - run: cr --entry server -1 ir
      name: Check server code

    - run: mkdir -p dist-server && cp compact.cirru dist-server && cp package.json dist-server/
      name: Copy server scripts

    - name: Upload web assets
      id: deploy
      uses: Pendect/action-rsyncer@v2.0.0
      env:
        DEPLOY_KEY: ${{secrets.rsync_private_key}}
      with:
        flags: '-avzr --progress'
        options: ''
        ssh_options: ''
        src: 'dist/*'
        dest: 'rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"

    - name: Upload server script
      id: deploy-server
      uses: Pendect/action-rsyncer@v2.0.0
      env:
        DEPLOY_KEY: ${{secrets.rsync_private_key}}
      with:
        flags: '-avzr --progress'
        options: ''
        ssh_options: ''
        src: 'dist-server/*'
        dest: 'rsync-user@tiye.me:/servers/timegrass/'

    - name: Display status from deploy
      run: echo "${{ steps.deploy-server.outputs.status }}"
